name: Project Diagnostics

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Environment Check
      run: |
        pwd
        php -v
        composer -V
        php -m
