name: Code Quality Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Quality Analysis
      run: |
        echo '=== Code Structure ==='
        find . -type f -name '*.php' | wc -l
        echo '=== File Distribution ==='
        find . -type f -exec dirname {} \; | sort | uniq -c
        echo '=== Recent Activity ==='
        git log --pretty=format:'%h - %an, %ar : %s' -5
