name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd='mysqladmin ping' --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, zip
    
    - uses: actions/checkout@v2
    
    - name: Copy .env
      run: cp .env.example .env
    
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
    
    - name: Generate Application Key
      run: php artisan key:generate
    
    - name: Run Migrations
      run: php artisan migrate --force
    
    - name: Run Tests
      run: php artisan test
