name: Security Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Security Check
      run: |
        echo '=== File Permissions ==='
        ls -la
        echo '=== User Sessions ==='
        who || true
        echo '=== Open Ports ==='
        netstat -tulpn || true
