name: Resource Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Resource Analysis
      run: |
        echo '=== CPU Stats ==='
        top -b -n 1
        echo '=== Disk Usage ==='
        df -h
        echo '=== Process Count ==='
        ps aux | wc -l
