name: Project Health Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Quick Stats
      run: |
        echo '=== Quick Project Stats ==='
        ls -l
        echo '=== Directory Tree ==='
        tree || true
