name: Project Health Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: Project Analysis
      run: |
        echo '=== PHP Info ==='
        php -v
        echo '=== Project Structure ==='
        ls -l
        echo '=== Composer Check ==='
        composer validate || true
