name: Code Quality Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Code Analysis
      run: |
        echo '=== Code Metrics ==='
        find . -type f -name '*.php' -exec wc -l {} \;
        echo '=== File Structure ==='
        find . -type f -name '*.php' -exec dirname {} \; | sort | uniq -c
        echo '=== Recent Changes ==='
        git diff --stat HEAD~1
