name: Project Diagnostics

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Environment Info
      run: |
        echo 'Environment Details:'
        uname -a
        pwd
        
    - name: Project Stats
      run: |
        echo 'Project Analysis:'
        find . -type f | wc -l
        du -sh .
