name: Advanced Project Analytics

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deep Analysis
      run: |
        echo '=== Repository Health ==='
        git shortlog -sn --no-merges
        echo '=== Code Distribution ==='
        find . -type f -name '*.php' -exec dirname {} \; | sort | uniq -c | sort -nr
