name: Project Health Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Repository Analysis
      run: |
        echo '=== Project Overview ==='
        ls -la
        echo '=== Git Info ==='
        git branch
        git describe --tags || true
