name: Project Analysis

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Project Stats
      run: |
        echo '=== Core Stats ==='
        find . -type f -name '*.php' | wc -l
        echo '=== Latest Changes ==='
        git log -3 --oneline
