name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        
    - name: Copy .env
      run: cp .env.example .env
        
    - name: Install Composer Dependencies
      run: composer install --no-scripts
        
    - name: Generate key
      run: php artisan key:generate
        
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
        
    - name: Create Database
      run: |
        touch database/database.sqlite
        php artisan migrate --force
        
    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
