name: Dependency Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Dependency Check
      run: |
        echo '=== Package Stats ==='
        find . -name 'composer.json' -o -name 'package.json'
        echo '=== File Types ==='
        find . -type f | grep -E '\.(php|js|css|json)$' | sort
        echo '=== Directory Structure ==='
        tree -L 2 || ls -R
