name: Network Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Network Analysis
      run: |
        echo '=== Network Stats ==='
        ifconfig || ip addr
        echo '=== Connection Status ==='
        ss -tuln
        echo '=== Route Table ==='
        netstat -r
