name: Test Coverage Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Test Analysis
      run: |
        echo '=== Test Files ==='
        find . -type f -name '*Test.php' | wc -l
        echo '=== Test Structure ==='
        find . -type f -name '*Test.php' -exec dirname {} \; | sort | uniq -c
        echo '=== Test Coverage ==='
        find . -type f -name '*.php' | grep -v 'Test.php' | wc -l
