name: Project Diagnostics

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Basic System Info
      run: |
        uname -a
        pwd
        whoami
        
    - name: Directory Structure
      run: |
        ls -la
        tree -L 2 || true
