name: Performance Benchmark

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Performance Analysis
      run: |
        echo '=== Response Time ==='
        time find . -type f
        echo '=== Memory Usage ==='
        free -h
        echo '=== Load Average ==='
        uptime
