name: Project Diagnostics

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Basic Checks
      run: |
        echo 'Starting diagnostics...'
        pwd
        ls -la
        
    - name: Repository Info
      run: |
        git branch
        git log -1
