name: Laravel CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Display PHP Version
      run: php -v
      
    - name: List Directory Contents
      run: ls -la
      
    - name: Check Composer
      run: composer --version
