name: Project Diagnostics

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: System Information
      run: |
        uname -a
        pwd
        whoami
        df -h
        
    - name: Project Analysis
      run: |
        ls -la
        find . -type f -name '*.php' | wc -l
        git status
