name: Advanced Metrics Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Advanced Analysis
      run: |
        echo '=== Repository Stats ==='
        git rev-list --count HEAD
        echo '=== File Analysis ==='
        find . -type f -exec file {} \;
        echo '=== Commit History ==='
        git log --graph --oneline -10
