name: Project Diagnostics

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: System Checks
      run: |
        php -v
        composer -V
        php -m
        df -h
        free -m
        
    - name: Project Structure
      run: |
        ls -la
        pwd
        whoami
