name: Project Diagnostics

on: [push]

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: System Check
      run: |
        echo '=== System Info ==='
        date
        whoami
        
    - name: File Analysis
      run: |
        echo '=== Project Stats ==='
        ls -R
        find . -maxdepth 3
