name: Application Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: App Analysis
      run: |
        echo '=== Code Stats ==='
        find . -type f -name '*.php' | wc -l
        echo '=== Git History ==='
        git log --oneline -5
        echo '=== Project Size ==='
        du -sh .
