name: Resource Monitor

on: [push]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Resource Check
      run: |
        echo '=== CPU Info ==='
        lscpu
        echo '=== Storage Stats ==='
        du -sh *
        echo '=== System Overview ==='
        uname -a
